name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama fuente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git checkout gh-pages  # Cambia esto a tu rama GitHub Pages
        cp -r * .git/ /path/to/your/html/files
        git add .
        git commit -m "Deployed website from GitHub Actions"
        git push
